work_dir = "~/work/my-video"

[download.yt-dlp.common]
extra_args = [
  "--cookies", "./cookies.txt",
  "--proxy", "socks5://192.168.3.6:2222/",
  "--remote-components", "ejs:github",
]

[transcribe]
demucs = true

[transcribe.whisperx]
language = "auto"
model = "large-v3"
model_dir = ""
