[project]
name = "my-video"
version = "0.1.0"
requires-python = ">=3.13,<3.14"
dependencies = [
    'audioop-lts; python_version >= "3.13"',
    "autocorrect-py>=2.0.1",
    "numpy>=2.2.6",
    "opencv-python>=4.10.0.84",
    "json-repair>=0.39.1",
    "openpyxl>=3.1.5",
    "openai>=1.55.3,<2",
    "pandas>=2.2.3",
    "pydub>=0.25.1",
    "rapidfuzz>=3.14.0",
    "tenacity>=8.2.0",
    "diskcache>=5.6.3",
    "spacy>=3.8.14",
    "torch>=2.8.0",
    "whisperx>=3.8.5",
    "demucs[dev] @ git+https://github.com/adefossez/demucs",
    "yt-dlp[default]>=2025.7.21",
]

[project.scripts]
my-video = "my_video.cli.main:main"

[dependency-groups]
dev = ["pytest>=8.0", "ruff>=0.4"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[tool.uv]
override-dependencies = [
    "torchaudio>=2.8.0",  # 强制覆盖 demucs 的 torchaudio<2.2
]
